#!/bin/bash
# gen-mono-hooklist.sh [libunity.so libmono.so] > compat/mono_symbols.h
#
# Emits the exact set of symbols apkenv must bridge from a host-built Mono, as a
# C array for compat/hostlib.c.
#
# The set is derived as: {symbols libunity.so leaves UNDEFINED} INTERSECT
# {symbols the apk's libmono.so DEFINES}. That is the real contract.
#
# Do NOT go back to matching the "mono_" prefix: libunity also resolves
# g_free (embedded eglib) and GC_delete_thread / GC_lookup_thread (Boehm) out of
# libmono, and a prefix filter silently drops them. Missing g_free is exactly
# what made the first bridged run die with
#   linker.c:1383| ERROR: 0 cannot locate 'g_free'... failed to link libunity.so
#
# With no arguments, reads the committed list at ../plan/tr2-mono-imports.txt.
set -e
cd "$(dirname "$0")/.."
NM=/opt/PalmPDK/arm-gcc/bin/arm-none-linux-gnueabi-nm
if [ -n "$1" ] && [ -n "$2" ]; then
    SRC="$(basename "$1") INTERSECT $(basename "$2")"
    SYMS=$(comm -12 \
        <($NM -D "$1" | awk '$1=="U"{print $2}' | sort -u) \
        <($NM -D --defined-only "$2" | awk '{print $3}' | sort -u))
elif [ -n "$1" ]; then
    echo "usage: $0 <libunity.so> <libmono.so>   (both, or neither)" >&2
    exit 2
else
    SRC="plan/tr2-mono-imports.txt (committed)"
    SYMS=$(sort -u ../plan/tr2-mono-imports.txt)
fi
N=$(echo "$SYMS" | wc -l)
cat <<EOF
/* GENERATED by tools/gen-mono-hooklist.sh - do not edit.
 * Source: $SRC
 * $N symbols that libunity.so resolves out of libmono.so.
 *
 * These are bridged to a natively-built (glibc) Mono runtime by
 * compat/hostlib.c; see plan/TEMPLERUN2-MONO.md.
 */
#ifndef COMPAT_MONO_SYMBOLS_H
#define COMPAT_MONO_SYMBOLS_H

static const char *const mono_bridge_symbols[] = {
EOF
echo "$SYMS" | sed 's/^/    "/; s/$/",/'
cat <<EOF
};

#define MONO_BRIDGE_SYMBOL_COUNT \\
    (sizeof(mono_bridge_symbols) / sizeof(mono_bridge_symbols[0]))

#endif /* COMPAT_MONO_SYMBOLS_H */
EOF
