#!/bin/bash
# gen-mono-hooklist.sh [libunity.so libmono.so] > compat/mono_symbols.h
#
# Emits the exact set of symbols apkenv must bridge from a host-built Mono, as a
# C array for compat/hostlib.c.
#
# The set is derived as: {symbols libunity.so leaves UNDEFINED} INTERSECT
# {symbols the apk's libmono.so DEFINES}. That is the real contract.
#
# Do NOT go back to matching the "mono_" prefix: libunity also resolves
# g_free (embedded eglib) and GC_delete_thread / GC_lookup_thread (Boehm) out of
# libmono, and a prefix filter silently drops them. Missing g_free is exactly
# what made the first bridged run die with
#   linker.c:1383| ERROR: 0 cannot locate 'g_free'... failed to link libunity.so
#
# With no arguments, emits the UNION of every committed per-game list,
# ../plan/*-mono-imports.txt. One binary hosts every Unity port, and each engine
# build imports a slightly different set: Aralon's Unity 4 libunity needs
# mono_string_new_len and mono_object_get_virtual_method, which TR2's never
# did - with only TR2's list, Aralon died at
#   linker.c:1383| ERROR: 0 cannot locate 'mono_string_new_len'...
# Extra names are harmless (a hook nobody imports is never bound). Regenerate a
# game's list with:  comm -12 <(libunity UND) <(host libmono DEF)
# and after regenerating, rebuild apkenv.o: build-webos.sh does not track headers.
set -e
cd "$(dirname "$0")/.."
NM=/opt/PalmPDK/arm-gcc/bin/arm-none-linux-gnueabi-nm
if [ -n "$1" ] && [ -n "$2" ]; then
    SRC="$(basename "$1") INTERSECT $(basename "$2")"
    SYMS=$(comm -12 \
        <($NM -D "$1" | awk '$1=="U"{print $2}' | sort -u) \
        <($NM -D --defined-only "$2" | awk '{print $3}' | sort -u))
elif [ -n "$1" ]; then
    echo "usage: $0 <libunity.so> <libmono.so>   (both, or neither)" >&2
    exit 2
else
    SRC="union of $(cd .. && ls plan/*-mono-imports.txt | tr '\n' ' ')(committed)"
    SYMS=$(cat ../plan/*-mono-imports.txt | sort -u)
fi
# Split the set. REQUIRED = names the shipped Unity 3.5 runtime
# (hostlibs/webos/libmono-webos.so) exports: a missing one stays fatal, as before.
# OPTIONAL = names only a newer runtime carries (RoboCop's Unity 4.2 Mono:
# mono_unity_liveness_* etc.), bridged only when the loaded runtime has them -
# so adding a Unity 4.2 game's list cannot make TR2/Aralon abort at startup.
BASE=${BASE_MONO:-hostlibs/webos/libmono-webos.so}
BASE_DEFS=$($NM -D --defined-only "$BASE" | awk '{print $3}' | sort -u)
REQ=$(comm -12 <(echo "$SYMS") <(echo "$BASE_DEFS"))
OPT=$(comm -23 <(echo "$SYMS") <(echo "$BASE_DEFS"))
N=$(echo "$REQ" | wc -l)
NO=$(echo "$OPT" | grep -c . || true)
cat <<EOF
/* GENERATED by tools/gen-mono-hooklist.sh - do not edit.
 * Source: $SRC
 * $N required + $NO optional symbols that libunity.so resolves out of libmono.so.
 * Required = exported by $BASE; optional = only newer runtimes
 * (compat/hostlib.h: apkenv_hostlib_bridge_optional).
 *
 * These are bridged to a natively-built (glibc) Mono runtime by
 * compat/hostlib.c; see plan/TEMPLERUN2-MONO.md.
 */
#ifndef COMPAT_MONO_SYMBOLS_H
#define COMPAT_MONO_SYMBOLS_H

static const char *const mono_bridge_symbols[] = {
EOF
echo "$REQ" | sed 's/^/    "/; s/$/",/'
cat <<EOF
};

#define MONO_BRIDGE_SYMBOL_COUNT \\
    (sizeof(mono_bridge_symbols) / sizeof(mono_bridge_symbols[0]))

static const char *const mono_bridge_symbols_optional[] = {
EOF
echo "$OPT" | grep . | sed 's/^/    "/; s/$/",/' || true
cat <<EOF
    NULL
};

#define MONO_BRIDGE_OPTIONAL_COUNT \\
    (sizeof(mono_bridge_symbols_optional) / sizeof(mono_bridge_symbols_optional[0]))

#endif /* COMPAT_MONO_SYMBOLS_H */
EOF
