#!/bin/bash
# gen-mono-hooklist.sh [libunity.so] > compat/mono_symbols.h
#
# Emits the list of mono_* symbols that libunity.so imports, as a C array for
# compat/hostlib.c to bridge. Generated mechanically so it cannot drift from the
# binary: re-run it if the game (or the Unity version) changes.
#
# With no argument, reads the committed list at ../plan/tr2-mono-imports.txt.
set -e
cd "$(dirname "$0")/.."
NM=/opt/PalmPDK/arm-gcc/bin/arm-none-linux-gnueabi-nm
if [ -n "$1" ]; then
    SRC="$1"
    SYMS=$($NM -D "$SRC" | awk '$1=="U" && $2 ~ /^mono_/ {print $2}' | sort -u)
else
    SRC="plan/tr2-mono-imports.txt (committed)"
    SYMS=$(sort -u ../plan/tr2-mono-imports.txt)
fi
N=$(echo "$SYMS" | wc -l)
cat <<EOF
/* GENERATED by tools/gen-mono-hooklist.sh - do not edit.
 * Source: $SRC
 * $N mono_* symbols imported by libunity.so.
 *
 * These are bridged to a natively-built (glibc) Mono runtime by
 * compat/hostlib.c; see plan/TEMPLERUN2-MONO.md.
 */
#ifndef COMPAT_MONO_SYMBOLS_H
#define COMPAT_MONO_SYMBOLS_H

static const char *const mono_bridge_symbols[] = {
EOF
echo "$SYMS" | sed 's/^/    "/; s/$/",/'
cat <<EOF
};

#define MONO_BRIDGE_SYMBOL_COUNT \\
    (sizeof(mono_bridge_symbols) / sizeof(mono_bridge_symbols[0]))

#endif /* COMPAT_MONO_SYMBOLS_H */
EOF
